# Generated by Django 4.1.7 on 2023-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdAdmins',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=60)),
                ('id_no', models.CharField(max_length=30)),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.TextField(max_length=200)),
                ('Course_code', models.CharField(max_length=20)),
            ],
        ),
    ]
